watson_prefix: w
debug: false
region_info_timeout: 5.0
group_ores_in_creative: true
chat_timeout: 0.1
ss_player_directory: true
ss_player_suffix: true
billboard_background: -1476395008
max_auto_pages: 10
teleport_command: /tppos %g %d %g
enabled: true
billboard_foreground: 2147483647
vectors_shown: true
reformat_query_results: true
recolour_query_results: true
post_count: 45
auto_page: true
pre_count: 45
ss_date_directory: ''
